# Generated by Django 2.2.4 on 2019-08-15 12:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studentId', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=300)),
                ('dead_line', models.DateTimeField()),
                ('country', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cgpa', models.FloatField()),
                ('portal_address', models.URLField()),
                ('important', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('faculty', 'Can access only their entries'), ('admin', 'Can access  department entries'), ('hod', 'Can access all Entries')),
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department_name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['id', 'email', 'role', 'first_name', 'last_name', 'department_name', 'created_at', 'password'],
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
