# Generated by Django 2.2.4 on 2019-08-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lor_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lor',
            old_name='studentId',
            new_name='student_id',
        ),
    ]
