# Generated by Django 2.2.4 on 2019-11-11 13:18

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cgpa', models.FloatField()),
                ('graduation_status', models.BooleanField(default=False)),
                ('degree', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfilePicture',
            fields=[
                ('picture', models.ImageField(blank=True, upload_to='student_profile_pics')),
                ('picture_url_google', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=250)),
                ('others_details', models.CharField(blank=True, max_length=250, null=True)),
                ('university_name', models.CharField(max_length=250)),
                ('program_name', models.CharField(max_length=250)),
                ('deadline', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyListLor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_done', django.contrib.postgres.fields.jsonb.JSONField()),
                ('projects_done', django.contrib.postgres.fields.jsonb.JSONField()),
                ('thesis_done', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.BooleanField(default=False)),
                ('application_status', models.CharField(choices=[('AP', 'Applied'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('CO', 'Completed'), ('EX', 'Expired')], default='AP', max_length=15)),
                ('others', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_15', models.BooleanField(default=False)),
                ('days_7', models.BooleanField(default=False)),
                ('days_3', models.BooleanField(default=False)),
                ('days_1', models.BooleanField(default=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_lor.Lor')),
            ],
            options={
                'unique_together': {('lor', 'faculty')},
            },
        ),
    ]
