# Generated by Django 2.2.4 on 2019-10-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultylistlor',
            name='days_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultylistlor',
            name='days_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultylistlor',
            name='days_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultylistlor',
            name='days_7',
            field=models.BooleanField(default=False),
        ),
    ]
