# Generated by Django 2.2.4 on 2019-11-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0002_auto_20191023_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='lor',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facultylistlor',
            name='application_status',
            field=models.CharField(choices=[('AP', 'Applied'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('CO', 'Completed'), ('EX', 'Expired')], default='AP', max_length=15),
        ),
    ]
