# Generated by Django 2.2.4 on 2019-09-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0002_auto_20190917_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lor',
            name='others_details',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
