# Generated by Django 2.2.4 on 2019-11-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0003_auto_20191104_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='lor',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
