# Generated by Django 2.2.4 on 2019-09-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0003_auto_20190917_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lor',
            name='others_details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
