# Generated by Django 2.2.4 on 2019-11-05 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191026_1450'),
        ('student_lor', '0004_lor_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfilePicture',
            fields=[
                ('picture', models.ImageField(upload_to='%student_id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
