# Generated by Django 2.2.4 on 2019-11-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0005_studentprofilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilepicture',
            name='picture',
            field=models.ImageField(upload_to='student_profile_pics'),
        ),
    ]
