# Generated by Django 2.2.4 on 2019-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0005_auto_20190919_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lor',
            name='portal_address',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='graduation_year',
            field=models.CharField(default=2021, max_length=5),
            preserve_default=False,
        ),
    ]
