# Generated by Django 2.2.4 on 2019-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0006_auto_20191105_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultylistlor',
            name='others',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
