# Generated by Django 2.2.4 on 2019-10-13 02:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0007_remove_studentdetails_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultylistlor',
            name='courses_done',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultylistlor',
            name='others',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultylistlor',
            name='projects_done',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultylistlor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facultylistlor',
            name='thesis_done',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
