# Generated by Django 2.2.4 on 2019-10-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0008_auto_20191013_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultylistlor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
