# Generated by Django 2.2.4 on 2019-10-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0009_auto_20191013_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultylistlor',
            name='status',
        ),
        migrations.AddField(
            model_name='facultylistlor',
            name='application_status',
            field=models.CharField(choices=[('AP', 'Applied'), ('AC', 'Accepted'), ('RE', 'Rejected')], default='AP', max_length=15),
        ),
        migrations.AlterField(
            model_name='facultylistlor',
            name='others',
            field=models.CharField(max_length=500),
        ),
    ]
