# Generated by Django 2.2.4 on 2019-10-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_lor', '0010_auto_20191013_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultylistlor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
